import { Inter } from "next/font/google";

import "./globals.css";
import AppShell from "@/components/appShell";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} `}>
        <AppShell>
          <div className="max-w-full md:max-w-[50%]  shadow-lg shadow-blue-500 bg-opacity-65 bg-bgCoverImage bg-no-repeat bg-center bg-cover mx-auto min-h-screen">
            {children}
          </div>
        </AppShell>
      </body>
    </html>
  );
}
